/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'webonise' at '11/3/16 4:06 PM' with Gradle 2.11
 *
 * @author webonise, @date 11/3/16 4:06 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
