/*
 * This Spock specification was auto generated by running the Gradle 'init' task
 * by 'webonise' at '11/3/16 4:06 PM' with Gradle 2.11
 *
 * @author webonise, @date 11/3/16 4:06 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
